// apps/angular-app/src/app/worksheet.component.ts
import { Component, ChangeDetectionStrategy, OnInit, OnDestroy } from '@angular/core'
import { WorksheetService } from './worksheet.services'
import createWorksheetKeyEventHandler from '../../../common/createWorksheetKeyEventHandler'

@Component({
  selector: 'app-worksheet',
  template: `
    <table class="worksheet" *ngIf="worksheet$ | async as worksheet">
      <thead>
        <tr>
          <th></th>
          <th *ngFor="let columnIndex of worksheet.maxCellAddress.columnIndex + 1 | appRange">{{columnIndex}}</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let rowIndex of worksheet.maxCellAddress.rowIndex + 1 | appRange">
          <th>{{rowIndex}}</th>
          <ng-container *ngFor="let columnIndex of worksheet.maxCellAddress.columnIndex + 1 | appRange">
            <ng-content *ngTemplateOutlet="cellTemplate; context: {
              rowIndex: rowIndex,
              columnIndex: columnIndex,
              active: rowIndex === worksheet.activeCellAddress.rowIndex && columnIndex === worksheet.activeCellAddress.columnIndex,
              content: worksheet.cellContents[rowIndex] && worksheet.cellContents[rowIndex][columnIndex] || ''
            }">
            </ng-content>
          </ng-container>
        </tr>
      </tbody>
    </table>

    <ng-template
      #cellTemplate
      let-rowIndex="rowIndex"
      let-columnIndex="columnIndex"
      let-active="active"
      let-content="content"
    >
      <td
        [attr.data-row-index]="rowIndex"
        [attr.data-column-index]="columnIndex"
        [class.active]="active"
        (click)="worksheetOperations.setActiveCellAddress(rowIndex, columnIndex)"
      >
        <input
          *ngIf="active else inactive"
          [value]="content"
          (input)="worksheetOperations.setActiveCellContent($event.target.value)"
          appAutoFocus
        >
        <ng-template #inactive>{{content}}</ng-template>
      </td>
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WorksheetComponent implements OnInit, OnDestroy {
  readonly worksheet$ = this._worksheet.worksheet$
  readonly worksheetOperations = this._worksheet.worksheetOperations
  private readonly _worksheetKeyEventHandler = createWorksheetKeyEventHandler(this.worksheetOperations)

  constructor(private readonly _worksheet: WorksheetService) {}

  ngOnInit() {
    window.addEventListener('keydown', this._worksheetKeyEventHandler)
  }

  ngOnDestroy() {
    window.removeEventListener('keydown', this._worksheetKeyEventHandler)
  }
}

// apps/vuejs-app/src/Worksheet.vue
<template lang="pug">
table.worksheet
  thead
    tr
      th
      th(
        v-for="(_, columnIndex) in worksheet.maxCellAddress.columnIndex + 1"
        :key="columnIndex"
      ) {{columnIndex}}
  tbody(
    @click="worksheetOperations.setActiveCellAddress(+$event.target.dataset.rowIndex, +$event.target.dataset.columnIndex)"
    @input="worksheetOperations.setActiveCellContent($event.target.value)"
  )
    tr(
      v-for="(_, rowIndex) in worksheet.maxCellAddress.rowIndex + 1"
      :key="rowIndex"
    )
      th {{rowIndex}}
      WorksheetCell(
        v-for="(_, columnIndex) in worksheet.maxCellAddress.columnIndex + 1"
        :key="columnIndex"
        :rowIndex="rowIndex"
        :columnIndex="columnIndex"
        :active="rowIndex === worksheet.activeCellAddress.rowIndex && columnIndex === worksheet.activeCellAddress.columnIndex"
        :content="worksheet.cellContents[rowIndex] && worksheet.cellContents[rowIndex][columnIndex]"
      )
</template>

<script lang="ts">
import Vue from 'vue'
import { WorksheetOperations } from '../../../usecase'
import createWorksheet from '../../common/createWorksheet'
import createWorksheetKeyEventHandler from '../../common/createWorksheetKeyEventHandler'
import WorksheetCell from './WorksheetCell.vue'

// Vue.js 2.x は配列要素の変更を検知できないので、現状の WorksheetOperations#setActiveCellContent() の実装では本当はダメです。
// ただし現状は入力確定時に必ずアクティブセルも合わせて変更されるために正しく動いているように見えてしまいます。
// Vue.js 3.x では配列要素の変更も検知できるようになるはずなので、このサンプルでは時間が解決することを信じて放置します。
export default Vue.extend({
  components: { WorksheetCell },
  data() {
    const worksheet = Vue.observable(createWorksheet())
    const worksheetOperations = new WorksheetOperations(mutate => mutate(worksheet))
    const worksheetKeyEventHandler = createWorksheetKeyEventHandler(worksheetOperations)
    return { worksheet, worksheetOperations, worksheetKeyEventHandler }
  },
  mounted() {
    window.addEventListener('keydown', this.worksheetKeyEventHandler)
  },
  beforeDestroy() {
    window.removeEventListener('keydown', this.worksheetKeyEventHandler)
  },
})
</script>
