// apps/react-app/src/Worksheet.tsx
import produce from 'immer'
import React from 'react'
import { Worksheet, WorksheetOperations } from '../../../usecase'
import createWorksheet from '../../common/createWorksheet'
import createWorksheetKeyEventHandler from '../../common/createWorksheetKeyEventHandler'

const mapRangeInclusive: <T>(max: number, callback: (n: number) => T) => T[] =
  (max, callback) => {
    const result = Array(max + 1)
    for (let i = 0; i <= max; i++) {
      result[i] = callback(i)
    }
    return result
  }

const WorksheetCell: React.SFC<{
  rowIndex: number
  columnIndex: number
  active: boolean
  content?: string
}> = ({ rowIndex, columnIndex, active, content }) => (
  <td
    className={active ? 'active' : ''}
    data-row-index={rowIndex}
    data-column-index={columnIndex}
  >
    {active ? <input defaultValue={content} autoFocus /> : content}
  </td>
)
const WorksheetCellMemoized = React.memo(WorksheetCell)

const WorksheetRow: React.SFC<{
  rowIndex: number
  row?: string[]
  activeCellIndex?: number
  maxColumnIndex: number
}> = ({ rowIndex, row, activeCellIndex, maxColumnIndex }) => (
  <tr>
    <th>{rowIndex}</th>
    {
      mapRangeInclusive(maxColumnIndex, columnIndex => (
        <WorksheetCellMemoized
          key={columnIndex}
          rowIndex={rowIndex}
          columnIndex={columnIndex}
          active={columnIndex === activeCellIndex}
          content={row && row[columnIndex]}
        />
      ))
    }
  </tr>
)
const WorksheetRowMemoized = React.memo(WorksheetRow)

const WorksheetTableHeader: React.SFC<{
  maxColumnIndex: number
}> = ({ maxColumnIndex }) => (
  <thead>
    <tr>
      <th></th>
      {mapRangeInclusive(maxColumnIndex, columnIndex => <th key={columnIndex}>{columnIndex}</th>)}
    </tr>
  </thead>
)

const WorksheetTable: React.SFC<{
  worksheet: Worksheet
  worksheetOperations: WorksheetOperations
}> = ({ worksheet: { maxCellAddress, activeCellAddress, cellContents }, worksheetOperations }) => (
  <table className='worksheet'>
    <WorksheetTableHeader maxColumnIndex={maxCellAddress.columnIndex} />
    <tbody
      onClick={React.useCallback(
        event => {
          const dataset = (event.target as HTMLElement).dataset
          worksheetOperations.setActiveCellAddress(+dataset.rowIndex!, +dataset.columnIndex!)
        },
        []
      )}
      onChange={React.useCallback(
        event => {
          if (event.target instanceof HTMLInputElement) {
            worksheetOperations.setActiveCellContent(event.target.value)
          }
        },
        []
      )}
    >
      {
        mapRangeInclusive(maxCellAddress.rowIndex, rowIndex => (
          <WorksheetRowMemoized
            key={rowIndex}
            rowIndex={rowIndex}
            row={cellContents[rowIndex]}
            activeCellIndex={rowIndex === activeCellAddress.rowIndex ? activeCellAddress.columnIndex : undefined}
            maxColumnIndex={maxCellAddress.columnIndex}
          />
        ))
      }
    </tbody>
  </table>
)
const WorksheetTableMemoized = React.memo(WorksheetTable)

export default () => {
  const [state, setState] = React.useState(createWorksheet())
  const worksheetOperations = new WorksheetOperations(
    mutate => setState(produce(mutate))
  )
  React.useEffect(() => {
    const handleKeyDown = createWorksheetKeyEventHandler(worksheetOperations)
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [])
  return (
    <WorksheetTableMemoized
      worksheet={state}
      worksheetOperations={worksheetOperations}
    />
  )
}

// apps/vuejs-app/src/Worksheet.vue
<template lang="pug">
table.worksheet
  thead
    tr
      th
      th(
        v-for="(_, columnIndex) in worksheet.maxCellAddress.columnIndex + 1"
        :key="columnIndex"
      ) {{columnIndex}}
  tbody(
    @click="worksheetOperations.setActiveCellAddress(+$event.target.dataset.rowIndex, +$event.target.dataset.columnIndex)"
    @input="worksheetOperations.setActiveCellContent($event.target.value)"
  )
    tr(
      v-for="(_, rowIndex) in worksheet.maxCellAddress.rowIndex + 1"
      :key="rowIndex"
    )
      th {{rowIndex}}
      WorksheetCell(
        v-for="(_, columnIndex) in worksheet.maxCellAddress.columnIndex + 1"
        :key="columnIndex"
        :rowIndex="rowIndex"
        :columnIndex="columnIndex"
        :active="rowIndex === worksheet.activeCellAddress.rowIndex && columnIndex === worksheet.activeCellAddress.columnIndex"
        :content="worksheet.cellContents[rowIndex] && worksheet.cellContents[rowIndex][columnIndex]"
      )
</template>

<script lang="ts">
import Vue from 'vue'
import { WorksheetOperations } from '../../../usecase'
import createWorksheet from '../../common/createWorksheet'
import createWorksheetKeyEventHandler from '../../common/createWorksheetKeyEventHandler'
import WorksheetCell from './WorksheetCell.vue'

// Vue.js 2.x は配列要素の変更を検知できないので、現状の WorksheetOperations#setActiveCellContent() の実装では本当はダメです。
// ただし現状は入力確定時に必ずアクティブセルも合わせて変更されるために正しく動いているように見えてしまいます。
// Vue.js 3.x では配列要素の変更も検知できるようになるはずなので、このサンプルでは時間が解決することを信じて放置します。
export default Vue.extend({
  components: { WorksheetCell },
  data() {
    const worksheet = Vue.observable(createWorksheet())
    const worksheetOperations = new WorksheetOperations(mutate => mutate(worksheet))
    const worksheetKeyEventHandler = createWorksheetKeyEventHandler(worksheetOperations)
    return { worksheet, worksheetOperations, worksheetKeyEventHandler }
  },
  mounted() {
    window.addEventListener('keydown', this.worksheetKeyEventHandler)
  },
  beforeDestroy() {
    window.removeEventListener('keydown', this.worksheetKeyEventHandler)
  },
})
</script>
